# Generated by Django 5.2.6 on 2025-09-29 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'вид объекта',
                'verbose_name_plural': 'Виды объектов',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Спорт',
                'verbose_name_plural': 'Виды спорта',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('location', models.TextField(blank=True, default='', verbose_name='Местоположение')),
                ('start_date', models.DateTimeField(blank=True, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='Дата конца')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.sport', verbose_name='Вид спорта')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('location', models.TextField(blank=True, default='', verbose_name='Местоположение')),
                ('start_date', models.DateTimeField(blank=True, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='Дата конца')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.sport', verbose_name='Вид спорта')),
            ],
            options={
                'verbose_name': 'Спортивное мероприятие',
                'verbose_name_plural': 'Спортивные мероприятия',
            },
        ),
        migrations.CreateModel(
            name='CityObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('location', models.TextField(blank=True, default='', verbose_name='Местоположение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.objecttype', verbose_name='Вид объекта')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.sport', verbose_name='Вид спорта')),
            ],
            options={
                'verbose_name': 'Спортивный объект',
                'verbose_name_plural': 'Спортивные объекты',
            },
        ),
    ]
