# Generated by Django 5.2.6 on 2025-09-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityobject',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='cityobject',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата конца'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата конца'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
    ]
