# Generated by Django 5.2.6 on 2025-10-19 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cityobject_lat_cityobject_lng_alter_event_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityobject',
            name='object_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='sport',
        ),
    ]
