# Generated by Django 5.2.6 on 2025-10-19 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_cityobject_object_type_remove_event_sport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityobject',
            name='sport',
        ),
        migrations.AddField(
            model_name='cityobject',
            name='object_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.objecttype', verbose_name='Вид объекта'),
            preserve_default=False,
        ),
    ]
