# Generated by Django 5.2.6 on 2025-10-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_cityobject_sport_cityobject_object_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityobject',
            name='sport',
            field=models.ManyToManyField(to='api.sport', verbose_name='Вид спорта'),
        ),
        migrations.AddField(
            model_name='event',
            name='sport',
            field=models.ManyToManyField(to='api.sport', verbose_name='Вид спорта'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='sport',
            field=models.ManyToManyField(to='api.sport', verbose_name='Вид спорта'),
        ),
    ]
