# Generated by Django 5.2.6 on 2025-10-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cityobject_sport_event_sport_invitation_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityobject',
            name='sport',
            field=models.ManyToManyField(related_name='sports_city_object', to='api.sport', verbose_name='Вид спорта'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sport',
            field=models.ManyToManyField(related_name='sports_event', to='api.sport', verbose_name='Вид спорта'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='sport',
            field=models.ManyToManyField(related_name='sports_invitation', to='api.sport', verbose_name='Вид спорта'),
        ),
    ]
