# Generated by Django 5.2.6 on 2025-12-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_cityobject_sport_alter_event_sport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type_event',
            field=models.CharField(choices=[('professional events', 'профессиональные события'), ('custom event', 'Пользовательское событие')], default='professional events', max_length=100, verbose_name='Тип события'),
        ),
    ]
